/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which sign-in options this deployment offers
         * @description So the shell can decide whether to render a GitHub button and a register link, rather than showing controls that lead to a 404.
         */
        get: operations["AuthController_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Requires a valid invite token while SIGNUP_MODE is invite_only. On success the session cookie is set, so the caller is signed in immediately.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out and destroy the current session */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the current password
         * @description Signs out every other session for this account.
         */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in as the public demo learner
         * @description Only when DEMO_MODE is on; otherwise this route does not exist. Hands out one shared throwaway account, part-way through a course, which is reset to its sample progress once nobody has used it for a while. Anything done here is deleted with that reset.
         */
        post: operations["AuthController_demoSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start signing in with GitHub
         * @description A redirect, not a fetch: navigate the browser here. Returns 404 when GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET are not configured.
         */
        get: operations["GithubOAuthController_start"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course-spec/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The bud.manifest.json JSON Schema
         * @description JSON Schema (draft 2020-12) for spec bud-course/1, plus the limits and validation codes the uploader enforces.
         */
        get: operations["CourseSpecController_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The catalog
         * @description Published courses only, newest last. Includes the caller’s progress for any course they are enrolled in.
         */
        get: operations["CoursesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One course, with its outline and session list
         * @description Unpublished courses are indistinguishable from missing ones.
         */
        get: operations["CoursesController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{slug}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrol in a course
         * @description Idempotent, and re-enrolling after leaving resumes rather than resets.
         */
        post: operations["CoursesController_enroll"];
        /**
         * Leave a course
         * @description Keeps progress, so re-enrolling picks up where it left off.
         */
        delete: operations["CoursesController_unenroll"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every course, including drafts and archived ones */
        get: operations["AdminCoursesController_list"];
        put?: never;
        /**
         * Upload a course package
         * @description Validates the zip and, if it passes, stores its files and creates a **draft** version. Publishing is a separate, deliberate step. A failed validation returns 200 with ok=false and the checklist — the upload worked, the package did not.
         */
        post: operations["AdminCoursesController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/courses/{id}/storage-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Storage keys learners actually use, against what the manifest declares
         * @description Undeclared keys are accepted at write time — rejecting would punish the learner for the author’s mistake — so drift surfaces here instead, in the author’s workflow, where it can be fixed without interrupting anybody.
         */
        get: operations["AdminCoursesController_storageKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Publish, unpublish, archive, or point at a different version
         * @description Publishing requires a version to publish: a course with no versions has nothing to show a learner.
         */
        patch: operations["AdminCoursesController_update"];
        trace?: never;
    };
    "/me/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the learner is working on
         * @description One round trip on purpose: this is the first screen after sign-in, and assembling it from three calls would let the slowest decide how the app feels.
         */
        get: operations["ProgressController_getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Streaks and the activity heatmap
         * @description Days are cut in the timezone the learner set, so an evening session counts for the evening it happened in. Signing in is not activity: only studying keeps a streak alive.
         */
        get: operations["ProgressController_getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses/{slug}/state/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * bridge: storage.get
         * @description A key that was never written returns `{ value: null }` rather than 404, because that is the shape the existing worksheets already handle.
         */
        get: operations["ProgressController_getState"];
        /**
         * bridge: storage.set
         * @description Whole value, last write wins — no partial patches. Keys the manifest did not declare are accepted: rejecting would punish the learner for the author’s mistake, since the worksheet turns a rejection into a small "not saved" flash that is easy to miss.
         */
        put: operations["ProgressController_setState"];
        post?: never;
        /**
         * bridge: storage.delete
         * @description Every worksheet’s "Clear saved work" calls this. Deleting a key that was never there succeeds — the caller wanted it gone, and it is gone.
         */
        delete: operations["ProgressController_deleteState"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses/{slug}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress through every session of a course */
        get: operations["ProgressController_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses/{slug}/sessions/{key}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The learner opened a session
         * @description Drives "continue where you left off". Never un-completes a finished session.
         */
        post: operations["ProgressController_open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses/{slug}/sessions/{key}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * bridge: bud.progress
         * @description Optional fine-grained progress. Never moves backwards.
         */
        post: operations["ProgressController_setFraction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses/{slug}/sessions/{key}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * bridge: bud.complete
         * @description The course suggests completion; the shell records it. Shell state is the source of truth and is never synced back into the course’s own blob.
         */
        post: operations["ProgressController_complete"];
        /** Reopen a session marked complete by mistake */
        delete: operations["ProgressController_uncomplete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses/{slug}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every note for a course, in session order
         * @description Sessions with no note are omitted rather than returned empty.
         */
        get: operations["NotesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses/{slug}/notes/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every note as one markdown file
         * @description Assembled here rather than in the shell: the ordering and the headings are the same decisions the list endpoint makes, and two implementations would drift.
         */
        get: operations["NotesController_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses/{slug}/sessions/{key}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The note for one session */
        get: operations["NotesController_get"];
        /**
         * Write the note for one session
         * @description Whole value, like the bridge. An empty body deletes the note.
         */
        put: operations["NotesController_save"];
        post?: never;
        /** Delete the note for one session */
        delete: operations["NotesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses/{slug}/deliverables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the learner has submitted for this course
         * @description No grading — "submitted" is the learner’s own claim.
         */
        get: operations["NotesController_listDeliverables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses/{slug}/sessions/{key}/deliverable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Submit or update a deliverable
         * @description Pass submitted:false to retract without losing the link.
         */
        put: operations["NotesController_saveDeliverable"];
        post?: never;
        /** Remove a deliverable entirely */
        delete: operations["NotesController_removeDeliverable"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            role: "learner" | "admin";
            avatarUrl: string | null;
            timezone: string;
            /** Format: date-time */
            createdAt: string;
        };
        UserEnvelope: {
            user: components["schemas"]["PublicUser"];
        };
        ChangePasswordResult: {
            revokedSessions: number;
        };
        AuthProviders: {
            password: boolean;
            github: boolean;
            demo: boolean;
            /** @enum {string} */
            signupMode: "invite_only" | "open" | "closed";
        };
        ErrorResponse: {
            statusCode: number;
            error: string;
            code: string;
            message: string;
            detail?: string;
            errors?: {
                path: string;
                message: string;
                code: string;
            }[];
            path: string;
            /** Format: date-time */
            timestamp: string;
        };
        ProgressSummary: {
            completedSessions: number;
            totalSessions: number;
            percent: number;
            lastSessionKey: string | null;
            /** Format: date-time */
            lastOpenedAt: string | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        CourseSummary: {
            slug: string;
            title: string;
            summary: string;
            level: string | null;
            estimatedHours: number | null;
            tags: string[];
            accentColor: string | null;
            coverUrl: string | null;
            sessionCount: number;
            version: string;
            enrollment: {
                completedSessions: number;
                totalSessions: number;
                percent: number;
                lastSessionKey: string | null;
                /** Format: date-time */
                lastOpenedAt: string | null;
                /** Format: date-time */
                startedAt: string;
                /** Format: date-time */
                completedAt: string | null;
            } | null;
        };
        CourseSession: {
            key: string;
            order: number;
            title: string;
            /** @enum {string|null} */
            weight: "light" | "medium" | "heavy" | null;
            deliverable: string | null;
            entryPath: string;
            /** @enum {string} */
            status: "not_started" | "in_progress" | "complete";
        };
        CourseDetail: {
            slug: string;
            title: string;
            summary: string;
            level: string | null;
            estimatedHours: number | null;
            tags: string[];
            accentColor: string | null;
            coverUrl: string | null;
            sessionCount: number;
            version: string;
            enrollment: {
                completedSessions: number;
                totalSessions: number;
                percent: number;
                lastSessionKey: string | null;
                /** Format: date-time */
                lastOpenedAt: string | null;
                /** Format: date-time */
                startedAt: string;
                /** Format: date-time */
                completedAt: string | null;
            } | null;
            outlineMarkdown: string | null;
            sessions: {
                key: string;
                order: number;
                title: string;
                /** @enum {string|null} */
                weight: "light" | "medium" | "heavy" | null;
                deliverable: string | null;
                entryPath: string;
                /** @enum {string} */
                status: "not_started" | "in_progress" | "complete";
            }[];
        };
        CourseList: {
            courses: {
                slug: string;
                title: string;
                summary: string;
                level: string | null;
                estimatedHours: number | null;
                tags: string[];
                accentColor: string | null;
                coverUrl: string | null;
                sessionCount: number;
                version: string;
                enrollment: {
                    completedSessions: number;
                    totalSessions: number;
                    percent: number;
                    lastSessionKey: string | null;
                    /** Format: date-time */
                    lastOpenedAt: string | null;
                    /** Format: date-time */
                    startedAt: string;
                    /** Format: date-time */
                    completedAt: string | null;
                } | null;
            }[];
            nextCursor: string | null;
        };
        AdminCourse: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            currentVersion: string | null;
            versionCount: number;
            enrollmentCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AdminCourseList: {
            courses: {
                /** Format: uuid */
                id: string;
                slug: string;
                title: string;
                /** @enum {string} */
                status: "draft" | "published" | "archived";
                currentVersion: string | null;
                versionCount: number;
                enrollmentCount: number;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            nextCursor: string | null;
        };
        ValidationResult: {
            /** @enum {string} */
            severity: "pass" | "warning" | "error";
            /** @enum {string} */
            code: "manifest_valid" | "entries_found" | "archive_safe" | "manifest_missing" | "manifest_invalid" | "entry_missing" | "duplicate_course_id" | "external_script" | "disallowed_extension" | "path_traversal" | "symlink" | "size_exceeded" | "cover_missing" | "checks_skipped";
            message: string;
            detail?: string;
        };
        IngestResult: {
            ok: boolean;
            results: {
                /** @enum {string} */
                severity: "pass" | "warning" | "error";
                /** @enum {string} */
                code: "manifest_valid" | "entries_found" | "archive_safe" | "manifest_missing" | "manifest_invalid" | "entry_missing" | "duplicate_course_id" | "external_script" | "disallowed_extension" | "path_traversal" | "symlink" | "size_exceeded" | "cover_missing" | "checks_skipped";
                message: string;
                detail?: string;
            }[];
            course: {
                /** Format: uuid */
                id: string;
                slug: string;
                title: string;
                /** @enum {string} */
                status: "draft" | "published" | "archived";
                version: string | null;
                filesStored: number;
            } | null;
        };
        CourseStorageKeys: {
            slug: string;
            version: string | null;
            declared: string[];
            undeclared: {
                key: string;
                learners: number;
            }[];
            unused: string[];
        };
        StateValue: {
            value: string | null;
        };
        SessionProgress: {
            sessionKey: string;
            /** @enum {string} */
            status: "not_started" | "in_progress" | "complete";
            fraction: number | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            completedAt: string | null;
        };
        SessionProgressList: {
            sessionKey: string;
            /** @enum {string} */
            status: "not_started" | "in_progress" | "complete";
            fraction: number | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            completedAt: string | null;
        }[];
        Dashboard: {
            continueCard: {
                slug: string;
                title: string;
                accentColor: string | null;
                sessionKey: string;
                sessionTitle: string;
                sessionOrder: number;
                weight: string | null;
                percent: number;
                resuming: boolean;
            } | null;
            courses: {
                slug: string;
                title: string;
                accentColor: string | null;
                coverUrl: string | null;
                completedSessions: number;
                totalSessions: number;
                percent: number;
                /** Format: date-time */
                lastOpenedAt: string | null;
                /** Format: date-time */
                completedAt: string | null;
                estimatedHours: {
                    total: number | null;
                    completed: number | null;
                };
            }[];
            recentNotes: {
                slug: string;
                courseTitle: string;
                sessionKey: string;
                sessionTitle: string | null;
                excerpt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            upcomingDeliverables: {
                slug: string;
                courseTitle: string;
                sessionKey: string;
                sessionTitle: string;
                asked: string;
                sessionComplete: boolean;
            }[];
            streak: {
                current: number;
                longest: number;
                lastActiveDate: string | null;
            };
            totals: {
                enrolledCourses: number;
                completedCourses: number;
                completedSessions: number;
                totalSessions: number;
                estimatedHours: {
                    total: number;
                    completed: number;
                };
            };
        };
        Activity: {
            timezone: string;
            today: string;
            streak: {
                current: number;
                longest: number;
                lastActiveDate: string | null;
            };
            days: {
                date: string;
                events: number;
                sessionsCompleted: number;
            }[];
            totals: {
                activeDays: number;
                events: number;
                sessionsCompleted: number;
            };
        };
        Note: {
            sessionKey: string;
            sessionTitle: string | null;
            sessionOrder: number | null;
            bodyMd: string;
            /** Format: date-time */
            updatedAt: string;
        } | null;
        NoteList: {
            sessionKey: string;
            sessionTitle: string | null;
            sessionOrder: number | null;
            bodyMd: string;
            /** Format: date-time */
            updatedAt: string;
        }[];
        Deliverable: {
            sessionKey: string;
            sessionTitle: string | null;
            asked: string | null;
            url: string;
            comment: string | null;
            /** Format: date-time */
            submittedAt: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        DeliverableList: {
            sessionKey: string;
            sessionTitle: string | null;
            asked: string | null;
            url: string;
            comment: string | null;
            /** Format: date-time */
            submittedAt: string | null;
            /** Format: date-time */
            updatedAt: string;
        }[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available providers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProviders"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    name: string;
                    inviteToken?: string;
                };
            };
        };
        responses: {
            /** @description Account created and signed in; the session cookie is set. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description Signup closed, or the invite is invalid/expired. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description That email address is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Signed in; the session cookie is set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description Invalid email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many failed attempts; try again later. See Retry-After. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out; the cookie is cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    currentPassword: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Password changed; every other session was signed out. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResult"];
                };
            };
            /** @description Current password is incorrect. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_demoSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed in as the demo learner. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
        };
    };
    GithubOAuthController_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description No valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CourseSpecController_schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The manifest schema and the limits that go with it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CoursesController_list: {
        parameters: {
            query?: {
                limit?: number;
                /** @description From the previous nextCursor. */
                cursor?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of published courses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseList"];
                };
            };
        };
    };
    CoursesController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The course. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description No published course with that slug. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CoursesController_enroll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrolled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSummary"];
                };
            };
            /** @description No published course with that slug. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CoursesController_unenroll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No longer enrolled. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCoursesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of courses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCourseList"];
                };
            };
        };
    };
    AdminCoursesController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Package accepted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description No file, or that version already exists. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCoursesController_storageKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Declared and observed keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseStorageKeys"];
                };
            };
        };
    };
    AdminCoursesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status?: "draft" | "published" | "archived";
                    currentVersion?: string;
                };
            };
        };
        responses: {
            /** @description The updated course. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCourse"];
                };
            };
        };
    };
    ProgressController_getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The dashboard. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    ProgressController_getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity for the requested window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
        };
    };
    ProgressController_getState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                /** @description Opaque course-chosen key. */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored value, or null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateValue"];
                };
            };
            /** @description Not enrolled. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProgressController_setState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
            };
        };
        responses: {
            /** @description Saved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not enrolled. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description storage_key_limit_reached — too many distinct keys. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description storage_value_too_large, or storage_quota_exceeded. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProgressController_deleteState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProgressController_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-session progress. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionProgressList"];
                };
            };
        };
    };
    ProgressController_open: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated progress. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionProgress"];
                };
            };
            /** @description unknown_session. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProgressController_setFraction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    fraction: number;
                };
            };
        };
        responses: {
            /** @description Updated progress. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionProgress"];
                };
            };
        };
    };
    ProgressController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated progress. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionProgress"];
                };
            };
        };
    };
    ProgressController_uncomplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated progress. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionProgress"];
                };
            };
        };
    };
    NotesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The notes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteList"];
                };
            };
            /** @description Not enrolled. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    NotesController_export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A markdown document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The note, or null when there is none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description unknown_session. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    NotesController_save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    bodyMd: string;
                };
            };
        };
        responses: {
            /** @description The saved note, or null if it was cleared. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    NotesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotesController_listDeliverables: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deliverables. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliverableList"];
                };
            };
        };
    };
    NotesController_saveDeliverable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                    comment?: string;
                    submitted?: boolean;
                };
            };
        };
        responses: {
            /** @description The deliverable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"];
                };
            };
        };
    };
    NotesController_removeDeliverable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A required dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
